// Import all the images in the directory statically
// import * as ExerciseImages from "../assets/img/exercises";

const Images = {
    exerciseImages: {

        "0": require("../assets/img/exercises/Barbell_Bench_Press.jpg"),
        "1": require("../assets/img/exercises/Cable_Low_Seated_Row.jpg"),
        "2": require("../assets/img/exercises/Pull-up.jpg"),
        "3": require("../assets/img/exercises/Lever_Preacher_Curl.jpg"),

        "Smith_Sprint_Lunge": require("../assets/img/exercises/Smith_Sprint_Lunge.jpg"),
        "Lever_Kneeling_Leg_Curl_(plate_loaded)": require("../assets/img/exercises/Lever_Kneeling_Leg_Curl_(plate_loaded).jpg"),
        "Sit_(wall)": require("../assets/img/exercises/Sit_(wall).jpg"),
        "Dumbbell_Squat": require("../assets/img/exercises/Dumbbell_Squat.jpg"),
        "Kettlebell_Goblet_Squat": require("../assets/img/exercises/Kettlebell_Goblet_Squat.jpg"),
        "Sled_45°_Leg_Wide_Press": require("../assets/img/exercises/Sled_45°_Leg_Wide_Press.jpg"),
        "Trap_Bar_Deadlift": require("../assets/img/exercises/Trap_Bar_Deadlift.jpg"),
        "Kettlebell_Swing": require("../assets/img/exercises/Kettlebell_Swing.jpg"),
        "Barbell_Full_Squat": require("../assets/img/exercises/Barbell_Full_Squat.jpg"),
        "Barbell_Hip_Thrust": require("../assets/img/exercises/Barbell_Hip_Thrust.jpg"),
        "Cable_Standing_Hip_Extension": require("../assets/img/exercises/Cable_Standing_Hip_Extension.jpg"),
        "Lever_Seated_Hip_Abduction": require("../assets/img/exercises/Lever_Seated_Hip_Abduction.jpg"),
        "Smith_Calf_Raise_(version_2)": require("../assets/img/exercises/Smith_Calf_Raise_(version_2).jpg"),
        "Lever_Seated_Calf_Raise_(plate_loaded)_(VERSION_2)": require("../assets/img/exercises/Lever_Seated_Calf_Raise_(plate_loaded)_(VERSION_2).jpg"),
        "Sled_Calf_Press_On_Leg_Press": require("../assets/img/exercises/Sled_Calf_Press_On_Leg_Press.jpg"),
        "Donkey_Calf_Raise": require("../assets/img/exercises/Donkey_Calf_Raise.jpg"),
        "Lever_Rotary_Calf": require("../assets/img/exercises/Lever_Rotary_Calf.jpg"),
        "Barbell_Clean-grip_Front_Squat": require("../assets/img/exercises/Barbell_Clean-grip_Front_Squat.jpg"),
        "Lever_Seated_Leg_Curl": require("../assets/img/exercises/Lever_Seated_Leg_Curl.jpg"),
        "Barbell_Straight_Leg_Deadlift": require("../assets/img/exercises/Barbell_Straight_Leg_Deadlift.jpg"),
        "Lever_Seated_Leg_Press_(VERSION_2)": require("../assets/img/exercises/Lever_Seated_Leg_Press_(VERSION_2).jpg"),
        "Bulgarian_Split_Squat": require("../assets/img/exercises/Bulgarian_Split_Squat.jpg"),
        "Dumbbell_Single_Leg_Split_Squat": require("../assets/img/exercises/Dumbbell_Single_Leg_Split_Squat.jpg"),
        "Dumbbell_One_Arm_Bent-over_Row": require("../assets/img/exercises/Dumbbell_One_Arm_Bent-over_Row.jpg"),
        "Cable_Wide_Pulldown": require("../assets/img/exercises/Cable_Wide_Pulldown.jpg"),
        "Dumbbell_Shrug": require("../assets/img/exercises/Dumbbell_Shrug.jpg"),
        "Pull-up": require("../assets/img/exercises/Pull-up.jpg"),
        "Barbell_Reverse_Grip_Bent_over_Row": require("../assets/img/exercises/Barbell_Reverse_Grip_Bent_over_Row.jpg"),
        "Chin-Up": require("../assets/img/exercises/Chin-Up.jpg"),
        "Cable_Low_Seated_Row": require("../assets/img/exercises/Cable_Low_Seated_Row.jpg"),
        "Inverted_Row": require("../assets/img/exercises/Inverted_Row.jpg"),
        "Dumbbell_Incline_Row": require("../assets/img/exercises/Dumbbell_Incline_Row.jpg"),
        "Cable_seated_row": require("../assets/img/exercises/Cable_seated_row.jpg"),
        "Cable_Seated_Wide-grip_Row": require("../assets/img/exercises/Cable_Seated_Wide-grip_Row.jpg"),
        "45_degree_hyperextension_(arms_in_front_of_chest)": require("../assets/img/exercises/45_degree_hyperextension_(arms_in_front_of_chest).jpg"),
        "Lever_Bent_over_Row_(plate_loaded)": require("../assets/img/exercises/Lever_Bent_over_Row_(plate_loaded).jpg"),
        "Lever_Front_Pulldown": require("../assets/img/exercises/Lever_Front_Pulldown.jpg"),
        "Lever_Neutral_Grip_Seated_Row_(plate_loaded)": require("../assets/img/exercises/Lever_Neutral_Grip_Seated_Row_(plate_loaded).jpg"),
        "Cable_Seated_High_Row_(V-bar)": require("../assets/img/exercises/Cable_Seated_High_Row_(V-bar).jpg"),
        "Weighted_Pull-Up": require("../assets/img/exercises/Weighted_Pull-Up.jpg"),
        "Lever_Lying_T-bar_Row": require("../assets/img/exercises/Lever_Lying_T-bar_Row.jpg"),
        "Lever_High_Row_(plate_loaded)": require("../assets/img/exercises/Lever_High_Row_(plate_loaded).jpg"),
        "Assisted_Pull-up": require("../assets/img/exercises/Assisted_Pull-up.jpg"),
        "Cable_Hammer_Curl_(with_rope)": require("../assets/img/exercises/Cable_Hammer_Curl_(with_rope).jpg"),
        "Dumbbell_Cross_Body_Hammer_Curl": require("../assets/img/exercises/Dumbbell_Cross_Body_Hammer_Curl.jpg"),
        "Dumbbell_Lateral_Raise": require("../assets/img/exercises/Dumbbell_Lateral_Raise.jpg"),
        "Dumbbell_Seated_Shoulder_Press": require("../assets/img/exercises/Dumbbell_Seated_Shoulder_Press.jpg"),
        "Dumbbell_Front_Raise": require("../assets/img/exercises/Dumbbell_Front_Raise.jpg"),
        "Barbell_Standing_Military_Press_(without_rack)": require("../assets/img/exercises/Barbell_Standing_Military_Press_(without_rack).jpg"),
        "Barbell_Curl": require("../assets/img/exercises/Barbell_Curl.jpg"),
        "Dumbbell_Biceps_Curl": require("../assets/img/exercises/Dumbbell_Biceps_Curl.jpg"),
        "Lever_Preacher_Curl": require("../assets/img/exercises/Lever_Preacher_Curl.jpg"),
        "Dumbbell_Incline_Biceps_Curl": require("../assets/img/exercises/Dumbbell_Incline_Biceps_Curl.jpg"),
        "Bench_dip_on_floor": require("../assets/img/exercises/Bench_dip_on_floor.jpg"),
        "Assisted_Triceps_Dip_(kneeling)": require("../assets/img/exercises/Assisted_Triceps_Dip_(kneeling).jpg"),
        "EZ_Barbell_Close_Grip_Preacher_Curl": require("../assets/img/exercises/EZ_Barbell_Close_Grip_Preacher_Curl.jpg"),
        "Barbell_Bench_Press": require("../assets/img/exercises/Barbell_Bench_Press.jpg"),
        "Barbell_Incline_Bench_Press": require("../assets/img/exercises/Barbell_Incline_Bench_Press.jpg"),
        "Dumbbell_Bench_Press": require("../assets/img/exercises/Dumbbell_Bench_Press.jpg"),
        "Dumbbell_Incline_Bench_Press": require("../assets/img/exercises/Dumbbell_Incline_Bench_Press.jpg"),
        "Dumbbell_Fly": require("../assets/img/exercises/Dumbbell_Fly.jpg"),
        "Dumbbell_Incline_Fly": require("../assets/img/exercises/Dumbbell_Incline_Fly.jpg"),
        "Lever_Seated_Fly": require("../assets/img/exercises/Lever_Seated_Fly.jpg"),
        "Push-up": require("../assets/img/exercises/Push-up.jpg"),
        "Barbell_Decline_Bench_Press": require("../assets/img/exercises/Barbell_Decline_Bench_Press.jpg"),
        "Cable_Standing_Fly": require("../assets/img/exercises/Cable_Standing_Fly.jpg"),
        "Dumbbell_Decline_Bench_Press": require("../assets/img/exercises/Dumbbell_Decline_Bench_Press.jpg"),
        "Decline_Push-Up": require("../assets/img/exercises/Decline_Push-Up.jpg"),
        "Cable_Low_Fly": require("../assets/img/exercises/Cable_Low_Fly.jpg"),
        "Dumbbell_Straight_Arm_Pullover": require("../assets/img/exercises/Dumbbell_Straight_Arm_Pullover.jpg"),
        "Lever_Seated_Shoulder_Press": require("../assets/img/exercises/Lever_Seated_Shoulder_Press.jpg"),
        "Lever_Seated_Reverse_Fly": require("../assets/img/exercises/Lever_Seated_Reverse_Fly.jpg"),
        "Dumbbell_Rear_Lateral_Raise": require("../assets/img/exercises/Dumbbell_Rear_Lateral_Raise.jpg"),
        "Cable_Front_Raise": require("../assets/img/exercises/Cable_Front_Raise.jpg"),
        "Cable_Standing_Cross-over_High_Reverse_Fly": require("../assets/img/exercises/Cable_Standing_Cross-over_High_Reverse_Fly.jpg"),
        "Front_Plank": require("../assets/img/exercises/Front_Plank.jpg"),
        "Cable_Kneeling_Crunch": require("../assets/img/exercises/Cable_Kneeling_Crunch.jpg"),
        "Crunch_Floor": require("../assets/img/exercises/Crunch_Floor.jpg"),
        "Jackknife_Sit-Up": require("../assets/img/exercises/Jackknife_Sit-Up.jpg"),
        "Air_bike": require("../assets/img/exercises/Air_bike.jpg"),
        "Lying_Leg_Raise": require("../assets/img/exercises/Lying_Leg_Raise.jpg"),
        "Captains_Chair_Straight_Leg_Raise": require("../assets/img/exercises/Captains_Chair_Straight_Leg_Raise.jpg"),
        "Lever_Seated_Crunch": require("../assets/img/exercises/Lever_Seated_Crunch.jpg"),
        "Seated_Leg_Raise": require("../assets/img/exercises/Seated_Leg_Raise.jpg"),
        "Rear_Decline_Bridge": require("../assets/img/exercises/Rear_Decline_Bridge.jpg"),
        "Hanging_Straight_Leg_Hip_Raise": require("../assets/img/exercises/Hanging_Straight_Leg_Hip_Raise.jpg"),
        "Reverse_Crunch": require("../assets/img/exercises/Reverse_Crunch.jpg"),
        "Weighted_Russian_Twist_(legs_up)": require("../assets/img/exercises/Weighted_Russian_Twist_(legs_up).jpg"),
        "Cable_Standing_Face_Pull_(with_rope)": require("../assets/img/exercises/Cable_Standing_Face_Pull_(with_rope).jpg")
    },
};
const getExercise = (name) => {
    return ExerciseImages[name]
}
export {getExercise}
export default Images

// export default function Images() {
//     var exerciseUri = (imgName) => {
//         return exercises[imgName]
//     }
// }
